# lib/sci/ia/include/ia/Makefile

LRUN=../../../../..

include $(LRUN)/config/make/Config.mak
INSTALL_SUBDIR=$(INSTALL_DIR_INC)/ia
DATA_FILES=ia.h ia_bezier.h ia_image.h ia_line.h ia_vector.h ia_signal.h
SUBDIRS=algo
include $(LRUN)/config/make/Directory.mak
