# lib/sci/ia/include/ia/algo/Makefile

LRUN=../../../../../..

include $(LRUN)/config/make/Config.mak
INSTALL_SUBDIR=$(INSTALL_DIR_INC)/ia/algo
DATA_FILES=ia_binarize.h ia_contours.h ia_convolution.h \
           ia_distance_transform.h ia_fft.h ia_morphology.h \
           ia_otsu.h
include $(LRUN)/config/make/Directory.mak
